[project]
name = "rio-weather-forecast"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "beautifulsoup4>=4.12.3",
    "polars>=1.20.0",
    "requests>=2.32.3",
]
